apiVersion: apps/v1
kind: Deployment
metadata:
  name: k60m-demo
  labels:
    app: k60m-demo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: k60m-demo
  template:
    metadata:
      labels:
        app: k60m-demo
    spec:
      containers:
      - name: express
        image: howinator/k60m-sample-app
        env:
        - name: TWITTER_BEARER_TOKEN
          valueFrom:
            secretKeyRef:
              name: twitter-creds
              key: TWITTER_BEARER_TOKEN
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: k60m-config
              key: NODE_ENV
        - name: USER_NAME
          valueFrom:
            configMapKeyRef:
              name: k60m-config
              key: USER_NAME
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 200m
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: k60m-demo
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: k60m-demo
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
